### ISSUE TITLE
Help with rules

### ISSUE THREAD

**Issue by wrender** [saltstack-formulas/firewalld-formula#13]
Thanks for the formula! Is it possible to re-use ports like this (below). Where I have port 3232 overlapping a service definition, and applied to two different groups of hosts?  I'm trying to get this to work, but it seems like when ports overlap it fails to render the SLS.  I'm in the process of setting up another test environment to test it more.

`# FirewallD pillar examples:
firewalld:
  enabled: True
  ipset: True
  default_zone: public

  services:
    sshcustom:
      short: sshcustom
      description: SSH
      ports:
        tcp:
          - 3232
          - 5252
   
    sshcustom2:
      short: sshcustom2
      description: SSH
      ports:
        tcp:
          - 3232
          - 522
    

  zones:
    public:
      short: Public
      description: "For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted."
      services:
      
     # Our first set of hosts
      {% if grains['id'] == 'salt.example.com' %}
        - sshcustom
        - sshcustom2
      {% endif %}

     #  Another set of hosts
     {% if grains['id'] == 'hosts.anotherdomain.com' %}
        - sshcustom
        - sshcustom2
      {% endif %}

        - http
        - https
        - salt-minion
      `

**Comment by aboe76** [comment]
Why not split the service definitions in three different xml's and make the names descriptive
and then mix and match in the pillar zones. I think that will be easier to manage in the long run. 

```
sshcustom3232:
  short: sshcustom3232
  description: SSH custom 3232
  ports:
    tcp:
      - 3232

sshcustom522:
  description: SSH custom 522
  ports:
    tcp:
      - 522

sshcustom5252:
  description: SSH custom 5252
  ports:
    tcp:
      - 5252
```
```
 # Our first set of hosts
  {% if grains['id'] == 'salt.example.com' %}
    - sshcustom3232
    - sshcustom522
  {% endif %}

 #  Another set of hosts
 {% if grains['id'] == 'hosts.anotherdomain.com' %}
    - sshcustom323
    - sshcustom5252
  {% endif %}

    - http
    - https
    - salt-minion
```
