### ISSUE TITLE
[BUG] XML entities are not encoded in service files

### ISSUE THREAD

**Issue by kbabioch** [saltstack-formulas/firewalld-formula#34]
`firewalld-formular` will render the following pillar data into a XML service file:

```
  services:
    monitoring:
      short: monitoring
      description: >-
        These ports are required for monitoring based on check_mk & NRPE.
      ports:
        tcp:
          - 5665
          - 6556
```
However it does not encode XML entities (such as `&` into ` `&amp;`, which leads to the service not being loaded into `firewalld` and the following error message:

```
ERROR: Failed to load service file
'/etc/firewalld/services/monitoring.xml': INVALID_SERVICE: not a valid
service file: not well-formed (invalid token): line 9, column 74
```

Hence, this service will not be loaded and the firewall behaves differently than expected.
