### ISSUE TITLE
[TALK] Why you did'nt use the states firewalld ? 

### ISSUE THREAD

**Issue by ArthurREGNARD** [saltstack-formulas/firewalld-formula#38]
I would like to know why you did'nt use the firewalld Modules and States? 

For exemple your doing in the init.sls file: 
```yaml
reload_firewalld:
  cmd.wait:
    - name: 'firewall-cmd --reload'
    - require:
      - service: service_firewalld
```

But the Modules do the same things:
```yaml
reload_firewalld:
  modules.wait:
    - name: firewalld.reload_rules
    - require:
      - service: service_firewalld
```

Why you don't use the states `firewalld.present` ? This states reload firewalld if something changed.
