### ISSUE TITLE
[BUG] Comment not present in zone xml file when using *_ports

### ISSUE THREAD

**Issue by mymindstorm** [saltstack-formulas/firewalld-formula#43]
### Formula commit hash / release tag

v1.0.0

### Versions reports (master & minion)

3000.2

### Pillar / config used

Working:

```yaml
firewalld:
  zones:
    public:
      ports:
        - comment: "test"
          port: 8080
          protocol: tcp
```

Not working:

```yaml
firewalld:
  zones:
    public:
      test_ports:
        - comment: "test"
          port: 8080
          protocol: tcp
```

---

### Describe the bug

When using `*_ports` instead of `ports` in pillar config, the comment is not present in rendered `/etc/firewalld/zones/public.xml`

### Steps to reproduce the bug

Use a the above pillar config.

### Expected behaviour

Comment is rendered to `/etc/firewalld/zones/public.xml`
